### PR TITLE
fixed typo in remove listener method

### PR DESCRIPTION
**Pull request by javiersearight**

### CODE REVIEW

**Review by Heesenp — APPROVED** [review]

**Review by BrianBatchelder — APPROVED** [review]
👍 
Thanks for finding and fixing this, Javier!

**Comment by BrianBatchelder** [comment]
@jsearight : Before we can merge this, we need you to fill out our [Contribution Agreement](https://docs.google.com/forms/d/e/1FAIpQLScErfiz-fXSPpVZ9r8Di2Tr2xDFxt5MgzUel0__9vqUgvko7Q/viewform). Thanks.

**Comment by javiersearight** [comment]
Filled out the contribution agreement. Thanks!

**Comment by BrianBatchelder** [comment]
Thanks again, @jsearight !

**Pull request merged**
